version: '3'

services:
  jovensambientalistas:
    image: jovensambientalistas
    build:
      context: jovens-ambientalistas-net-core
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    links:
      - mysql
    environment:
      MYSQL_SERVER_NAME: mysqlDb
    env_file:
      - jovens-ambientalistas-net-core/secrets.env
  mysql:
    container_name: mysqlDb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
  appbuild:
    